### ISSUE TITLE
gdb doesn't disassemble correctly

### ISSUE THREAD

**Issue by projectgus** [projectgus/openocd#1]
This is maybe an issue with the crosstool-ng-built xtensa-lx106-elf-gdb, not with openocd, but it effects the usefulness of openocd all the same. Or it may be that openocd is reading the 24-bit instructions wrong due to alignment shenanigans.

xtensa-lx106-elf-objdump -d can successfully disassemble, so it mustn't be too hard to bring it into gdb as well.

**Comment by jcmvbkbc** [comment]
xtensa-lx106-elf-gdb works well with QEMU, and it's the same code that is used natively in linux, where it works well too.

**Comment by projectgus** [comment]
Yeah, you're right. This was late night brain-fail shoot-the-messanger.

openocd's target_read_buffer_default will split a 3 byte read into smaller reads, so that was never going to work. Easy to fix.
