### ISSUE TITLE
Create watchdog workaround for esp8266

### ISSUE THREAD

**Issue by projectgus** [projectgus/openocd#3]
"Currently normal SDK programs reset 1 second after halting due to the watchdog, which is hard to disable permanently because it re-enables each time the background task feeds it. Which makes openocd kind of useless for debugging SDK apps. I'm [testing with this very basic watchdog-free program](https://gist.github.com/projectgus/45d4cc4140e72f1e5a51) for now, but it should be possible to add an esp8266 hook that disables the watchdog on halt."

**Comment by jcmvbkbc** [comment]
According to ets_wdt_disable clearing bit 0 of the word at 0x60000900 should be enough to disable the watchdog.
